import React, { useState } from 'react';
import ArticleIcon from '@mui/icons-material/Article';
import DownloadIcon from '@mui/icons-material/Download';
import ContentCopyIcon from '@mui/icons-material/ContentCopy';
import CheckCircleIcon from '@mui/icons-material/CheckCircle';
import CloseIcon from '@mui/icons-material/Close';
import AccessTimeIcon from '@mui/icons-material/AccessTime';
import ErrorOutlineIcon from '@mui/icons-material/ErrorOutline';
import BuildIcon from '@mui/icons-material/Build';
import TimelineIcon from '@mui/icons-material/Timeline';
import CircularProgress from '@mui/material/CircularProgress';

function IncidentReport({ analysis, logs, onClose }) {
  const [copied, setCopied] = useState(false);
  const [isGenerating, setIsGenerating] = useState(false);
  const [report, setReport] = useState(null);

  const generateReport = () => {
    setIsGenerating(true);

    // Simulate report generation delay
    setTimeout(() => {
      const errorAnalysis = analysis?.analysis || {};
      const relatedLogs = logs
        .filter(l => l.level === 'ERROR' || l.level === 'CRITICAL')
        .slice(-20);

      const reportData = {
        generatedAt: new Date().toISOString(),
        title: `Incident Report: ${errorAnalysis.errorType || 'System Error'}`,
        summary: {
          severity: errorAnalysis.severity || 'MEDIUM',
          service: errorAnalysis.originService || 'Unknown',
          errorType: errorAnalysis.errorType || 'Unknown',
          timestamp: new Date().toISOString(),
          status: 'Investigating'
        },
        rootCause: {
          description: errorAnalysis.rootCause || 'Root cause analysis pending',
          technicalDetails: errorAnalysis.technicalDetails || 'N/A',
          affectedComponents: errorAnalysis.propagationPath || []
        },
        timeline: relatedLogs.map(log => ({
          timestamp: log.timestamp,
          service: log.service,
          level: log.level,
          message: log.message?.substring(0, 200)
        })),
        resolution: {
          immediateActions: errorAnalysis.immediateActions || [],
          longTermFixes: errorAnalysis.longTermFixes || [],
          preventionMeasures: errorAnalysis.preventionMeasures || []
        },
        metrics: {
          totalErrors: relatedLogs.length,
          affectedServices: [...new Set(relatedLogs.map(l => l.service))],
          timeToDetection: '< 1 minute',
          estimatedImpact: errorAnalysis.severity === 'CRITICAL' ? 'High' : 'Moderate'
        }
      };

      setReport(reportData);
      setIsGenerating(false);
    }, 1500);
  };

  const formatReportAsText = () => {
    if (!report) return '';

    return `
================================================================================
                           INCIDENT REPORT
================================================================================

Generated: ${new Date(report.generatedAt).toLocaleString()}

SUMMARY
-------
Title: ${report.title}
Severity: ${report.summary.severity}
Service: ${report.summary.service}
Error Type: ${report.summary.errorType}
Status: ${report.summary.status}

ROOT CAUSE ANALYSIS
-------------------
${report.rootCause.description}

Technical Details:
${report.rootCause.technicalDetails}

Affected Components:
${report.rootCause.affectedComponents.map((c, i) => `  ${i + 1}. ${c}`).join('\n')}

TIMELINE
--------
${report.timeline.map(t =>
  `[${new Date(t.timestamp).toLocaleTimeString()}] ${t.service} (${t.level}): ${t.message}`
).join('\n')}

RESOLUTION
----------
Immediate Actions:
${report.resolution.immediateActions.map((a, i) => `  ${i + 1}. ${a}`).join('\n')}

Long-term Fixes:
${report.resolution.longTermFixes.map((f, i) => `  ${i + 1}. ${f}`).join('\n')}

Prevention Measures:
${report.resolution.preventionMeasures.map((m, i) => `  ${i + 1}. ${m}`).join('\n')}

METRICS
-------
Total Errors: ${report.metrics.totalErrors}
Affected Services: ${report.metrics.affectedServices.join(', ')}
Time to Detection: ${report.metrics.timeToDetection}
Estimated Impact: ${report.metrics.estimatedImpact}

================================================================================
                    Generated by LogLens AI
================================================================================
`.trim();
  };

  const copyReport = async () => {
    try {
      await navigator.clipboard.writeText(formatReportAsText());
      setCopied(true);
      setTimeout(() => setCopied(false), 2000);
    } catch (err) {
      console.error('Copy failed:', err);
    }
  };

  const downloadReport = () => {
    const text = formatReportAsText();
    const blob = new Blob([text], { type: 'text/plain' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = `incident-report-${new Date().toISOString().split('T')[0]}.txt`;
    a.click();
    URL.revokeObjectURL(url);
  };

  const downloadJSON = () => {
    const blob = new Blob([JSON.stringify(report, null, 2)], { type: 'application/json' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = `incident-report-${new Date().toISOString().split('T')[0]}.json`;
    a.click();
    URL.revokeObjectURL(url);
  };

  return (
    <div className="fixed inset-0 bg-black/50 backdrop-blur-sm flex items-center justify-center z-50 p-4">
      <div className="card w-full max-w-3xl max-h-[90vh] flex flex-col">
        {/* Header */}
        <div className="flex items-center justify-between p-4 border-b border-border-dark">
          <div className="flex items-center gap-2">
            <ArticleIcon sx={{ fontSize: 20, color: '#3B82F6' }} />
            <h2 className="font-semibold text-text-primary">Incident Report</h2>
          </div>
          <button
            onClick={onClose}
            className="p-2 hover:bg-bg-hover rounded-lg transition-colors text-text-secondary"
          >
            <CloseIcon sx={{ fontSize: 20 }} />
          </button>
        </div>

        {/* Content */}
        <div className="flex-1 overflow-y-auto p-6">
          {!report && !isGenerating && (
            <div className="text-center py-12">
              <ArticleIcon sx={{ fontSize: 64, color: '#737373', marginBottom: 16 }} />
              <h3 className="text-lg font-medium text-text-primary mb-2">
                Generate Incident Report
              </h3>
              <p className="text-text-muted mb-6 max-w-md mx-auto">
                Create a comprehensive incident report including root cause analysis,
                timeline, and recommended actions.
              </p>
              <button
                onClick={generateReport}
                className="btn btn-primary"
              >
                Generate Report
              </button>
            </div>
          )}

          {isGenerating && (
            <div className="text-center py-12">
              <CircularProgress size={48} sx={{ color: '#3B82F6', marginBottom: 16 }} />
              <p className="text-text-primary">Generating incident report...</p>
              <p className="text-text-muted text-sm mt-2">Analyzing logs and correlating events</p>
            </div>
          )}

          {report && (
            <div className="space-y-6">
              {/* Summary */}
              <div className="card p-4 bg-bg-medium">
                <div className="flex items-center gap-2 mb-3">
                  <ErrorOutlineIcon sx={{ fontSize: 18, color: '#EF4444' }} />
                  <h3 className="font-medium text-text-primary">Summary</h3>
                </div>
                <div className="grid grid-cols-2 gap-4 text-sm">
                  <div>
                    <span className="text-text-muted">Severity:</span>
                    <span className={`ml-2 badge ${
                      report.summary.severity === 'CRITICAL' ? 'badge-error' :
                      report.summary.severity === 'HIGH' ? 'badge-error' :
                      report.summary.severity === 'MEDIUM' ? 'badge-warning' : 'badge-info'
                    }`}>
                      {report.summary.severity}
                    </span>
                  </div>
                  <div>
                    <span className="text-text-muted">Service:</span>
                    <span className="text-text-primary ml-2">{report.summary.service}</span>
                  </div>
                  <div>
                    <span className="text-text-muted">Error Type:</span>
                    <span className="text-text-primary ml-2">{report.summary.errorType}</span>
                  </div>
                  <div>
                    <span className="text-text-muted">Status:</span>
                    <span className="text-status-warning ml-2">{report.summary.status}</span>
                  </div>
                </div>
              </div>

              {/* Root Cause */}
              <div className="card p-4">
                <div className="flex items-center gap-2 mb-3">
                  <BuildIcon sx={{ fontSize: 18, color: '#3B82F6' }} />
                  <h3 className="font-medium text-text-primary">Root Cause</h3>
                </div>
                <p className="text-text-secondary text-sm mb-3">
                  {report.rootCause.description}
                </p>
                {report.rootCause.technicalDetails && (
                  <div className="bg-bg-darkest rounded-lg p-3 text-xs font-mono text-text-muted">
                    {report.rootCause.technicalDetails}
                  </div>
                )}
              </div>

              {/* Timeline */}
              <div className="card p-4">
                <div className="flex items-center gap-2 mb-3">
                  <TimelineIcon sx={{ fontSize: 18, color: '#0891B2' }} />
                  <h3 className="font-medium text-text-primary">Timeline</h3>
                  <span className="text-xs text-text-muted">({report.timeline.length} events)</span>
                </div>
                <div className="space-y-2 max-h-48 overflow-y-auto">
                  {report.timeline.slice(0, 10).map((event, i) => (
                    <div key={i} className="flex items-start gap-2 text-sm">
                      <AccessTimeIcon sx={{ fontSize: 14, marginTop: 2 }} className="text-text-muted" />
                      <span className="text-text-muted whitespace-nowrap">
                        {new Date(event.timestamp).toLocaleTimeString()}
                      </span>
                      <span className={`font-medium ${
                        event.level === 'ERROR' || event.level === 'CRITICAL'
                          ? 'text-status-error'
                          : 'text-text-secondary'
                      }`}>
                        [{event.service?.replace('kubewhisper-', '')}]
                      </span>
                      <span className="text-text-secondary truncate">{event.message}</span>
                    </div>
                  ))}
                </div>
              </div>

              {/* Resolution */}
              <div className="card p-4">
                <div className="flex items-center gap-2 mb-3">
                  <CheckCircleIcon sx={{ fontSize: 18, color: '#22C55E' }} />
                  <h3 className="font-medium text-text-primary">Recommended Actions</h3>
                </div>
                <div className="space-y-3">
                  {report.resolution.immediateActions.length > 0 && (
                    <div>
                      <h4 className="text-xs text-text-muted uppercase mb-2">Immediate</h4>
                      <ul className="space-y-1">
                        {report.resolution.immediateActions.map((action, i) => (
                          <li key={i} className="text-sm text-text-secondary flex items-start gap-2">
                            <span className="text-status-warning">-</span>
                            {action}
                          </li>
                        ))}
                      </ul>
                    </div>
                  )}
                  {report.resolution.longTermFixes.length > 0 && (
                    <div>
                      <h4 className="text-xs text-text-muted uppercase mb-2">Long-term</h4>
                      <ul className="space-y-1">
                        {report.resolution.longTermFixes.map((fix, i) => (
                          <li key={i} className="text-sm text-text-secondary flex items-start gap-2">
                            <span className="text-status-info">-</span>
                            {fix}
                          </li>
                        ))}
                      </ul>
                    </div>
                  )}
                </div>
              </div>
            </div>
          )}
        </div>

        {/* Footer */}
        {report && (
          <div className="flex items-center justify-between p-4 border-t border-border-dark">
            <span className="text-xs text-text-muted">
              Generated {new Date(report.generatedAt).toLocaleString()}
            </span>
            <div className="flex items-center gap-2">
              <button onClick={copyReport} className="btn btn-secondary flex items-center gap-2">
                {copied ? (
                  <CheckCircleIcon sx={{ fontSize: 16, color: '#22C55E' }} />
                ) : (
                  <ContentCopyIcon sx={{ fontSize: 16 }} />
                )}
                {copied ? 'Copied!' : 'Copy'}
              </button>
              <button onClick={downloadReport} className="btn btn-secondary flex items-center gap-2">
                <DownloadIcon sx={{ fontSize: 16 }} />
                TXT
              </button>
              <button onClick={downloadJSON} className="btn btn-primary flex items-center gap-2">
                <DownloadIcon sx={{ fontSize: 16 }} />
                JSON
              </button>
            </div>
          </div>
        )}
      </div>
    </div>
  );
}

export default IncidentReport;
